import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = (props) => {
  return (
    <div className="py-0 px-8">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen py-16 px-0 flex-1 flex flex-col justify-center">
        <h1 className="m-0 leading-[1.15] text-[4rem] text-center">
          Welcome to{" "}
          <a
            className="text-primary hover:underline focus:underline active:underline "
            href="https://nextjs.org"
          >
            Next.js!
          </a>
        </h1>

        <p className="text-center my-4 mx-0  leading-[1.5] text-2xl ">
          Get started by editing{" "}
          <code className="rounded p-3 text-[1.1rem] bg-secondaryWhite  ">
            pages/index.tsx
          </code>
        </p>

        {/* GRID */}
        <div className=" w-full flex-col tablet:flex-row  flex items-center justify-center tablet:flex-wrap tablet:max-w-[800px] ">
          <a
            href="https://nextjs.org/docs"
            className={
              "hover:text-primary hover:border-primary focus:text-primary focus:border-primary active:text-primary active:border-primary  m-4 p-6 text-left text-inherit border border-[#eaeaea] rounded-[10px] max-w-[300px] "
            }
          >
            <h2 className="mt-0 mr-0 mb-4 ml-0 text-2xl">
              Documentation &rarr;
            </h2>
            <p className="m-0 text-xl leading-[1.5]">
              Find in-depth information about Next.js features and API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn"
            className={
              "hover:text-primary hover:border-primary focus:text-primary focus:border-primary active:text-primary active:border-primary m-4 p-6 text-left text-inherit border border-[#eaeaea] rounded-[10px] max-w-[300px] "
            }
          >
            <h2 className="mt-0 mr-0 mb-4 ml-0 text-2xl">Learn &rarr;</h2>
            <p className="m-0 text-xl leading-[1.5]">
              Learn about Next.js in an interactive course with quizzes!
            </p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={
              "hover:text-primary hover:border-primary focus:text-primary focus:border-primary active:text-primary active:border-primary m-4 p-6 text-left text-inherit border border-[#eaeaea] rounded-[10px] max-w-[300px] "
            }
          >
            <h2 className="mt-0 mr-0 mb-4 ml-0 text-2xl">Examples &rarr;</h2>
            <p className="m-0 text-xl leading-[1.5]">
              Discover and deploy boilerplate example Next.js projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={
              "hover:text-primary hover:border-primary focus:text-primary focus:border-primary active:text-primary active:border-primary m-4 p-6 text-left text-inherit border border-[#eaeaea] rounded-[10px] max-w-[300px] "
            }
          >
            <h2 className="mt-0 mr-0 mb-4 ml-0 text-2xl">Deploy &rarr;</h2>
            <p className="m-0 text-xl leading-[1.5]">
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className="flex flex-1 py-8 px-0 border-t border-[#eaeaea] justify-center items-center">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          className="flex justify-center items-center grow"
        >
          Powered by{" "}
          <span className="h-[1em] ml-2">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export const getServerSideProps = async (context) => {
  const res = await fetch("http://localhost:3000/sendjson");

  const data = await res.json();
  console.log(data);
  return { props: { data } };
};

export default Home;
